### ISSUE TITLE
JST not defined at start of compiled file.

### ISSUE THREAD

**Issue by Boughtmanatee5** [vadimi/underscore-templates-msbuild#1]
When the compiler runs it adds.

```
JST = JST || {};
JST["archiveItemTpl"] = function(obj){ *template* }
```

Shouldn't it be 

```
var JST = JST || {}
```

So that it's declared as a variable?

**Comment by vadimi** [comment]
@Boughtmanatee5 `var` keyword is not required for global variables. Are you having any issues with current declaration?

**Comment by Boughtmanatee5** [comment]
@vadimi It doesn't work when using Strict Mode. The global object has to be referenced when setting a property onto it. I think Setting it as a variable would be a good solution or setting it as window.JST.

**Comment by vadimi** [comment]
Ah, yes, that makes sense for strict mode. I added a change that will wrap templates into a closure. Basically generated file will look something like that:

``` javascript
(function(global) {
global.JST = global.JST || {};
global.JST["layout"] = function(obj){
var __t,__p='',__j=Array.prototype.join,print=function(){__p+=__j.call(arguments,'');};
with(obj||{}){
__p+='<div>\r\n    layout\r\n</div>\r\n';
}
return __p;
};
})(this);
```

Let me know if it helps and I'll publish new package.

**Comment by Boughtmanatee5** [comment]
Awesome, works great on my end.

**Comment by vadimi** [comment]
Great, thanks! New NuGet package has been published.
